#+TITLE: Statement of Interest
#+SUBTITLE: EUTypes Summer School 2017
#+AUTHOR: Mario Román
#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \setlength{\parindent}{0cm}

/To the organising comitee of EUTypes Summer School,/

$\quad$

I am a student of two bachelor degrees in Mathematics and Computer
Science. I am working on homological algebra and category theory. My
research is supported by an introduction to research grant of the
Spanish government. I am writing my bachelor thesis on lambda calculus
and category theory applied to functional programming.

My primary interest lies in the field of type systems as foundations
of mathematics and logic. I started learning Haskell three years
ago, at the same time I began learning category theory. Since
then, I have implemented lambda calculus-based interpreters on
Haskell, written  proofs on Coq and started studying about type
theory. I am very interested in the introduction to Agda, and the
courses about the logic of type systems and Homotopy Type Theory.

This summer school would be a great opportunity for me to gain some
advanced training on type theory, proof assistants and their
underlying mathematics; to help me decide what specific topics of
research I would like to work on during my career, and to network with students
and professors working on this field.

$\quad$

/Sincerely, Mario Román./

